import matplotlib.pyplot as plt
import scipy.linalg as la
import numpy as np
elist = np.load('e_list.npy')
Fid_noisy_list = np.load('Fid_noisy_list.npy')
Fid_RM_list = np.load('Fid_RM_list.npy')
a_n, b_n = np.polyfit(np.log(elist[1:60]), np.log(1-Fid_noisy_list[1:60]), 1)
print(a_n,b_n)
a_rm, b_rm = np.polyfit(np.log(elist[1:]), np.log(1-Fid_RM_list[1:]), 1)
print(a_rm,b_rm)
fig = plt.figure()
fig.set_size_inches(12, 8)
plt.plot(elist, 1-Fid_noisy_list, '-', label='Without RM', linewidth=3,color='orange')
plt.plot(elist, 1-Fid_RM_list, '-', label='With RM', linewidth=3,color='blue')
plt.plot(elist, np.exp(np.real(b_n))*elist**np.real(a_n), '-.', label=f'Fit without RM: 1-F'+r'$\rm _s$'+f'={np.exp(np.real(b_n)):.3f}'+r'$\epsilon$'+fr'$^{{{np.real(a_n):.3f}}}$', color='red',linewidth=3)
plt.plot(elist, np.exp(np.real(b_rm))*elist**np.real(a_rm), '--', label=f'Fit with RM: 1-F'+r'$\rm _s$'+f'={np.exp(np.real(b_rm)):.3f}'+r'$\epsilon$'+fr'$^{{{np.real(a_rm):.3f}}}$', color='red',linewidth=3)

plt.xlabel(r'Measurement Error $\epsilon$', fontsize=28)
plt.ylabel(r'Steering Infidelity $1-F_{\rm s}$', fontsize=28)
# plt.ylim(0.95, 1.003)
plt.xlim(0.0001, 0.01)

plt.xscale('log')
plt.yscale('log')
plt.yticks([1e-7, 1e-5, 1e-3, 1e-1], [r'$10^{-7}$', r'$10^{-5}$',r'$10^{-3}$',r'$10^{-1}$'], fontsize=24)
plt.xticks([0.0001, 0.001, 0.01], ['0.0001', '0.001', '0.01'], fontsize=24)
plt.legend(fontsize=18)
# plt.grid()
plt.title(r'Steering Infidelity vs Measurement Error $(p=0.8, \theta=\pi/8)$', fontsize=24)
plt.savefig('Steering_Infidelity_vs_Measurement_Error_log.pdf', dpi=300)
# plt.show()

plt.legend([], frameon=False) 
fig.set_size_inches(3, 2)
plt.xscale('linear')
plt.yscale('linear')
plt.xticks([0, 0.01], ['0', '0.01'], fontsize=12)
plt.ylim(0, 0.045)
plt.yticks([0, 0.02, 0.04], ['0', '0.02', '0.04'], fontsize=12)
plt.title('')
plt.xlabel(r'$\epsilon$', fontsize=14)
plt.ylabel(r'$1-F_{\rm s}$', fontsize=14)
plt.subplots_adjust(left=0.25) 
plt.subplots_adjust(bottom=0.25)
plt.savefig('Steering_Infidelity_vs_Measurement_Error_linear.pdf', dpi=300)
plt.show()
# plt.close()
# print(Fid_RM_list)